---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py

language: python
python:
  - "3.6"

before_script:
  - pip3 install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

services:
  - postgresql

script:
  - python manage.py test

# safelist
branches:
  only:
    - newstaging
