---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - google-chrome-stable --headless --disable-gpu

language: python
python:
  - "3.6"

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &


addons:
  chrome: stable

before_script:
  - pip3 install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

after_failure:
  - if [ -f tests/tests.log ]; then cat tests/tests.log && sleep 10; fi
  - echo == End of test log ==


env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

services:
  - postgresql

script:
  - python manage.py test

# safelist
branches:
  only:
    - newP10
