---
language: python 
python: 
  - "3.6"

before_script:
  - pip3 install -r /PurBeurre/requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - /PurBeurre/manage.py test

# safelist
branches:
  only:
    - staging
