---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - export PATH=$PATH:chromedriver.exe
  - chmod +x manage.py

language: python
python:
  - "3.6"

before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

services:
  - postgresql

script:
  - python manage.py test

# safelist
branches:
  only:
    - staging
