---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python
python:
  - "3.6"

addons:
  chrome: stable 

services:
  - postgresql

before_script:
  - pip3 install -r requirements.txt
  - psql -c "CREATE DATABASE purbeurre;" -U postgres
  - psql -c "CREATE ROLE root SUPERUSER LOGIN CREATEDB;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - psql -c "SELECT * FROM information_schema.tables WHERE table_schema = 'public';"
  - psql -c "INSERT INTO auth_user(password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)	VALUES ('Niam1989', null, false, 'LeUsernameTest', 'David', 'Joseph', 'monami@gmail.com', false, true, '2020-05-08 21:38:12.033215+00')"
  - python manage.py fill_db


env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

services:
  - postgresql

script:
  - python manage.py test

# safelist
branches:
  only:
    - newP10
