---
before_install:
  - chmod +x ./PurBeurre/manage.py
  - cd ./Purbeurre
language: python
python:
  - "3.6"

before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

services:
  - postgresql

script:
  - manage.py test

# safelist
branches:
  only:
    - staging
