---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python
python:
  - "3.6"

addons:
  chrome: stable 

before_script:
  - pip3 install -r requirements.txt
  - sudo psql -c "CREATE DATABASE purbeurre;" -U postgres
  - sudo psql -c "CREATE USER root WITH PASSWORD 'Hamzamal89';" -U postgres
  - postgres=# ALTER USER root WITH SUPERUSER; ALTER ROLE 
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py fill_db


env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

services:
  - postgresql

script:
  - python manage.py test

# safelist
branches:
  only:
    - newP10
