---
---
os:
  linux

dist:
  xenial

language: python 
python: 
  - "3.6"

before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - ./manage.py test

# safelist
branches:
  only:
    - staging
