---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python

python:
  - "3.6"

addons:
  chrome: stable 

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

before_script:
  - pip3 install -r requirements.txt
  - psql -c "CREATE ROLE root SUPERUSER LOGIN CREATEDB";
  - psql -c "ALTER USER root WITH PASSWORD 'Hamzamal89'";
  - psql -c "CREATE DATABASE purbeurre WITH OWNER = root ENCODING = 'UTF8' CONNECTION LIMIT = -1;"
  - psql purbeurre < output.sql
  - psql -U root -d purbeurre -f output.sql
  - python manage.py makemigrations foodfacts
  - python manage.py migrate
  - psql -c "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;"


script:
  - python manage.py fill_db
  - python manage.py test

# safelist
branches:
  only:
    - newP10
