---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python
python:
  - "3.6"

addons:
  chrome: stable 

services:
  - postgresql

before_script:
  - pip3 install -r requirements.txt
  - psql -c "CREATE ROLE root SUPERUSER LOGIN CREATEDB";
  - psql -c "ALTER USER root WITH PASSWORD 'Hamzamal89'";
  - psql -c "CREATE DATABASE purbeurre WITH OWNER = root ENCODING = 'UTF8'CONNECTION LIMIT = -1";

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

script:
  - python manage.py makemigrations
  - python manage.py showmigrations 
  - python manage.py migrate
  - psql -c "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;" 
  - psql -c "INSERT INTO auth_user(password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)	VALUES ('Niam1989', null, false, 'LeUsernameTest', 'David', 'Joseph', 'monami@gmail.com', false, true, '2020-05-08 21:38:12.033215+00')" 
  - python manage.py fill_db
  - python manage.py test -k

# safelist
branches:
  only:
    - newP10
