---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py

language: python
python:
  - "3.6"

before_script:
  - pip3 install -r requirements.txt
  - pip install chromedriver-py

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings"

services:
  - postgresql

script:
  - python manage.py test

# safelist
branches:
  only:
    - newstaging
