---
[
  {
    "os": "linux",
    "language": {
      "python": [
        "3.6"
      ]
    },
    "dist": "xenial",
    "before_script": [
      "pip3 install -r requirements.txt"
    ],
    "services": [
      "postgresql"
    ],
    "script": [
      "./manage.py test"
    ],
    "branches": {
      "only": [
        "staging"
      ]
    },
    "env": [
      {
        "DJANGO_SETTINGS_MODULE": "\"purbeurre.settings\""
      }
    ]
  }
]
